name: Extract
description: Extract compiled test classes from JAR.
inputs:
  test-archive:
    description: JAR file name, with extension, without directory.
    required: true
  extract-to:
    description: Destination directory.
    required: true
runs:
  using: composite
  steps:
    - run: unzip ${{ github.action_path }}/archives/${{ inputs.test-archive }} -d ${{ inputs.extract-to }}
      shell: bash
      